name: flutter_mordern_chat_ui

description: A modern customizable messaging UI package for Flutter.

version: 1.0.0

homepage: https://github.com/yourusername/flutter_mordern_chat_ui
repository: https://github.com/yourusername/flutter_mordern_chat_ui

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: